# If the admission webhook is enabled, then a post-install step is required
# to generate and install the secret in the operator namespace.

# In the post-install hook, the token corresponding to the operator service account
# is used to authenticate with the Kubernetes API server to install the secret bundle.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .OperatorName }}
  namespace: {{ .Namespace }}
  labels:
    app.kubernetes.io/name: {{ .OperatorName }}
    app.kubernetes.io/instance: {{ .Name }}
    app.kubernetes.io/version: {{ .Params.operatorVersion }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .OperatorName }}
      app.kubernetes.io/instance: {{ .Name }}
      app.kubernetes.io/version: {{ .Params.operatorVersion }}
  strategy:
    type: Recreate
  template:
    metadata:
    {{- if .Params.enableMetrics }}
      annotations:
      {{- if .Params.enableMetrics }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Params.metricsPort }}"
        prometheus.io/path: {{ .Params.metricsEndpoint }}
      {{- end }}
    {{- end }}
      labels:
        app.kubernetes.io/name: {{ .OperatorName }}
        app.kubernetes.io/instance: {{ .Name }}
        app.kubernetes.io/version: {{ .Params.operatorVersion }}
      initializers:
        pending: []
    spec:
      {{- if .Params.createOperatorServiceAccount }}
      serviceAccountName: {{ .Name }}-{{ .Params.operatorServiceAccountName }}
      {{- else }}
      serviceAccountName: {{ .Params.operatorServiceAccountName }}
      {{- end }}
      {{- if .Params.enableWebhook }}
      volumes:
        - name: webhook-certs
          secret:
            secretName: spark-webhook-certs
      {{- end }}
      containers:
      - name: sparkoperator
        image: {{ .Params.operatorImageName }}:{{ .Params.operatorVersion }}
        imagePullPolicy: {{ .Params.imagePullPolicy }}
        {{- if .Params.enableWebhook }}
        volumeMounts:
          - name: webhook-certs
            mountPath: /etc/webhook-certs
        {{- end }}
        {{- if .Params.enableMetrics }}
        ports:
          - containerPort: {{ .Params.metricsPort }}
        {{ end }}
        args:
        - -v={{ .Params.logLevel }}
        {{- if (ne .Params.sparkJobNamespace "") }}
        - -namespace={{ .Params.sparkJobNamespace }}
        {{- else }}
        - -namespace={{ .Namespace }}
        {{- end }}
        - -ingress-url-format={{ .Params.ingressUrlFormat }}
        - -controller-threads={{ .Params.controllerThreads }}
        - -resync-interval={{ .Params.resyncInterval }}
        - -logtostderr
        {{- if .Params.enableMetrics }}
        - -enable-metrics=true
        - -metrics-labels=app_type
        - -metrics-port={{ .Params.metricsPort }}
        - -metrics-endpoint={{ .Params.metricsEndpoint }}
        - -metrics-prefix={{ .Params.metricsPrefix }}
        {{- end }}
        - -enable-batch-scheduler={{ .Params.enableBatchScheduler }}
        {{- if .Params.enableWebhook }}
        - -enable-webhook=true
        - -webhook-svc-namespace={{ .Namespace }}
        - -webhook-port={{ .Params.webhookPort }}
        - -webhook-svc-name={{ .OperatorName }}-webhook
        - -webhook-config-name={{ .OperatorName }}-webhook-config
        {{- end }}