apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: mock-task-runner
spec:
  type: Scala
  mode: cluster
  image: gcr.io/spark-operator/spark:v2.4.4-gcs-prometheus
  imagePullPolicy: Always
  mainClass: MockTaskRunner
  mainApplicationFile: "https://infinity-artifacts.s3.amazonaws.com/scale-tests/dcos-spark-scala-tests-assembly-2.4.0-20190325.jar"
  arguments:
    - "5"
    - "120"
  sparkConf:
    "spark.scheduler.maxRegisteredResourcesWaitingTime": "2400s"
    "spark.scheduler.minRegisteredResourcesRatio": "1.0"
    "spark.eventLog.enabled": "true"
    "spark.eventLog.dir": "/opt/spark/work-dir"
  sparkVersion: "2.4.4"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    memory: "512m"
    labels:
      version: 2.4.4
    serviceAccount: spark-driver
  executor:
    cores: 1
    instances: 5
    memory: "512m"
    labels:
      version: 2.4.4
  volumes:
   - name: historyserver-storage
     persistentVolumeClaim:
       claimName: spark-events-pvc
  volumeMounts:
   - mountPath: "/opt/spark/work-dir"
     name: historyserver-storage
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: "/prometheus/jmx_prometheus_javaagent-0.11.0.jar"
      port: 49151
---
apiVersion: v1
kind: Service
metadata:
  name: mock-task-runner-service-monitor
  labels:
    "spark/servicemonitor": "true"
spec:
  ports:
    - port: 49151
      name: metrics
  clusterIP: None
  selector:
    "sparkoperator.k8s.io/app-name": mock-task-runner
